### ISSUE TITLE
Android: nativeView not defined, undefined

### ISSUE THREAD

**Issue by joey0xx** [dapriett/nativescript-google-maps-sdk#164]
After I build the app and install on android it shows the error in the title; nativeView not defined, undefined. I wasn't getting that error a few hours ago but now I'm getting the error. Didn't change anything except for the api key. Using angular.

**Comment by nicHoch** [comment]
I also have that error after the latest update of the map plugin.

**Comment by dapriett** [comment]
Are you using the latest version (2.0.6)?  Please include any logs, error stacks, or sample code.

**Comment by ADjenkov** [comment]
+1 
@dapriett  I'm also getting this now after updating to 2.0.6. 

No special scenario:
1. `tns create maptest --ng`
2. setting up the plugin just as `Setup Android API Key` with my own apikey
3. Registering with 

`import { registerElement } from "nativescript-angular/element-registry";
// Important - must register MapView plugin in order to use in Angular templates
registerElement("MapView", () => require("nativescript-google-maps-sdk").MapView);
`

4. Adding it to my page :
` MapView></MapView>`

5. `tns run android` 
![image](https://cloud.githubusercontent.com/assets/5860190/26284489/51d387dc-3e45-11e7-8ead-0486d336ce87.png)
I see no exceptions or console outputs. Nothing

PS: All this was working 10 minutse ago with `nativescript-google-maps-sdk 2.0.3`

**Comment by joey0xx** [comment]
Yes, got the error with version 2.0.6. Everything as @ADjenkov says. For now I'm just using version 2.0.3

**Comment by dapriett** [comment]
Try 2.0.7 - I must have incorrectly published 2.0.6.  Let me know if there are still issues.

**Comment by ADjenkov** [comment]
I can confirm that it works now with 2.0.7. Thanks for the fast reactions and responses!
