### ISSUE TITLE
Problem with the "settings.myLocationButtonEnabled" property

### ISSUE THREAD

**Issue by raschdiaz** [dapriett/nativescript-google-maps-sdk#182]
The button does not appear even though the property "myLocationButtonEnabled" its in true.

When i console the "settings.myLocationButtonEnabled" property, appear in true, i am doing something wrong?.

**Comment by dapriett** [comment]
You'll need to make sure your app has the correct permissions to see the user's location first, otherwise the google sdk won't show it.  See the demo for references:

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/demo/app/App_Resources/Android/AndroidManifest.xml#L19

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/demo/app/App_Resources/iOS/Info.plist#L46

https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/demo/app/main-page.js#L16

**Comment by raschdiaz** [comment]
It worked!, thank you!.
