### ISSUE TITLE
google play services issue w/ other plugins

### ISSUE THREAD

**Issue by dklinzing** [dapriett/nativescript-google-maps-sdk#34]
It looks like this plugin currently conflicts w/ the following two plugins due to the google play services version referenced.  Both plugins below are currently referencign 8.4.0.  
Push Plugin: https://github.com/NativeScript/push-plugin
Google Analytics Plugin: https://github.com/sitefinitysteve/nativescript-googleanalytics

Can this be specifically set in this plugin to the following so it also uses the same version as both plugins above?
dependencies {
	compile 'com.google.android.gms:play-services-maps:8.4.0'
}

**Comment by dapriett** [comment]
I have it currently setup to use the latest version installed `compile 'com.google.android.gms:play-services-maps:+'`.  You can maybe try uninstalling any later versions of the sdk with the Android SDK Manager, then I believe it should use 8.4.0.

Maybe it would be best if they changed their plugins to do the same, that way you're always using the latest installed.  Otherwise, I'm not sure the best way to keep them all in sync.

**Comment by dklinzing** [comment]
Unfortunately we're building using the Telerik Platform, so we don't have control over the google play service version installed.  I'll check w/ the other plugin developers to see if they can use latest version installed.

**Comment by mini-eggs** [comment]
I was just having this issue between three plugins. admob + push-notifications + google-maps-sdk.

In the include.gradle for each plugin I replaced the previous junk with this:
dependencies {
    compile "com.google.android.gms:play-services-ads:9.0.0"
}

tns platform remove android 
tns run android
Should spin it right!

**Comment by dapriett** [comment]
Looks like this issue is resolved - at least for this plugin.

**Comment by dapriett** [comment]
(https://github.com/dapriett/nativescript-google-maps-sdk/commit/9a92655e8b33c51f575f24e7103919bea1c7c794).

Hopefully that solve your issues.  If so, maybe you can ask the other plugins that depend on Google Play Services to reference the same property.
