### ISSUE TITLE
Android demo not working

### ISSUE THREAD

**Issue by svs** [dapriett/nativescript-google-maps-sdk#73]
```tns build android```

fails with 

```
AAPT: No resource found that matches the given name (at 'theme' with value '@style/LaunchScreenTheme').
```

Noob android developer here. Pls help?

**Comment by poorcoder** [comment]
I think you have problems in your manifest file... If you are trying to make Launch Screen take a look at this [Launch Screen](https://gist.github.com/poorcoder/c400ed1d8ecc568f6292f1d3865b977e) gist...

**Comment by svs** [comment]
I'm only trying to make the included demo work. I haven't changed any of the code.

**Comment by jiwonyune** [comment]
I have the same error with the demo.

`AAPT: No resource found that matches the given name (at 'theme' with value '@style/LaunchScreenTheme').`

**Comment by SittingFox** [comment]
So you're trying to build an APK instead of running it directly in an emulator?

Just gave it a try, and it worked for me.
```
git clone https://github.com/dapriett/nativescript-google-maps-sdk.git
cd nativescript-google-maps-sdk/demo
tns build android
```

And it was successful. `platforms/android/src/main/res/values/styles.xml` doesn't seem to be there before the process, probably created during the build.

I'd double check that everything is cool with `tns doctor`. That would be my first thought.

**Comment by eppisapia** [comment]
Hi
On android isn't showing the maps it doesn't thrown an error or anything. Just don't paint the map

**Comment by dapriett** [comment]
`platforms/android/src/main/res/values/styles.xml` is a nativescript generate file, not from this plugin.  Guessing something wrong with the nativescript installation.  If you're still having issues, probably better off posting an issue here https://github.com/NativeScript/NativeScript
