### ISSUE TITLE
Android is not painting the map

### ISSUE THREAD

**Issue by eppisapia** [dapriett/nativescript-google-maps-sdk#78]
Hello.

On Android it isn't painting the map, on console throw the message that its's setting the marks (haven't a bucle).
- Map is inside an Absolute Layout, full Length to cover all page with just a text label overlaying it.
- Generic Api key
- on iOS work perfectly
- Tested on Device and Emulator on both isn't showing

Any clue what it could be?

Regards

**Comment by SittingFox** [comment]
My setup that works with Android is something like this:
```
<AbsoluteLayout width="100%" height="100%">
    <GridLayout width="100%" height="100%">
        <MapView></MapView>
    </GridLayout>
    <!-- things that go over map here -->
</AbsoluteLayout>    
```

I'm not sure how much of that is necessary, but it's worth a shot, huh?

**Comment by eppisapia** [comment]
Yes, I haven't trouble with the Layout. It work on iOS perfectly but on Android it doesn't show the map  

It doesn't throw and error, exception or any system message.

**Comment by SittingFox** [comment]
Well, my map wasn't appearing for me and also no errors. I fiddled with the layout with different combinations, and then that worked. That's all I'm saying. That MapView might be picky with the layout.

I can't remember if it was just Android or both, but it works fine for me now on both.

Otherwise, I guess someone else will have to have a guess. It's hard to figure out something if no errors are thrown, since the errors are the clues. Example code might prove helpful.

**Comment by dapriett** [comment]
Try viewing the android logs (`adb logcat`), see if there are any errors in there.

**Comment by codyboaz** [comment]
@SittingFox did you ever figure the issue out? I am having the same problem.

**Comment by SittingFox** [comment]
Heya @codyboaz,

Yes, what I said in my first post works for me, having the `MapView` within its own `GridView`. One of the other view tags may also work, maybe?

**Comment by dapriett** [comment]
Closing this issue, reopen if you're still having issues.
